repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --locked --all -- --check --color always
        language: system
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Check if all files pass clippy
        entry: cargo clippy --locked --all-targets --no-deps -- -D warn
        language: system
        pass_filenames: false
