name: "Deploy"
on:
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
      staging_image_repo:
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Generate Version
        id: version
        run: |
          echo "version=tip-$(date +%Y%m%d.%H%M%S).${GITHUB_SHA:0:4}" >> "$GITHUB_OUTPUT"
  build:
    needs: [generate-version]
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write # for pushing to GHCR
    with:
      output: image
      platforms: linux/amd64,linux/arm64
      meta-images: ${{ inputs.staging_image_repo }}
      cache: true
      cache-mode: max
      cache-scope: envoyproxy
      meta-tags: |
        type=ref,event=branch
        type=raw,value=${{needs.generate-version.outputs.version}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          username: ${{ secrets.GITHUB_TOKEN }}
  finalize:
    environment: release
    needs: [generate-version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create tag
        id: create-tag
        run: |
          git tag ${{ needs.generate-version.outputs.version }} ${{ github.sha }}
      - name: Install regctl
        uses: iarekylew00t/regctl-installer@v4
      - name: Recompute meta tags
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ inputs.staging_image_repo }}
          sep-tags: " "
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=raw,value=${{needs.generate-version.outputs.version}}
      - name: "Copy images"
        run: |
          for source in ${{ steps.meta.outputs.tags }}; do
            # shellcheck disable=SC2001
            dest="$(echo "$source" | sed -e 's,${{ inputs.staging_image_repo }},${{ inputs.image_repo }},')"
            echo "Copying $source to $dest"
            regctl image copy "$source" "$dest"
          done
      - name: Push Tag
        run: git push origin tag ${{ needs.generate-version.outputs.version}}
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          target_commitish: ${{ github.sha }}
          tag_name: ${{ needs.generate-version.outputs.version }}
          generate_release_notes: true
          make_latest: true
      - name: send push
        run: |
          curl -f \
          -d token=${{ secrets.PUSHOVER_TOKEN }} \
          -d user=${{ secrets.PUSHOVER_USER }} \
          -d priority=0 \
          -d message="${{github.repository}} ${{ github.ref_name }} deployed" \
          -d ttl=86400 \
          -d sound=bike \
           https://api.pushover.net/1/messages.json
