name: "On Push to Main"
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  deploy-to-ghcr:
    needs: [ci]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
